/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.dados;

/**
 *
 * @author thayrone
 */
public class scriptCriaBanco {

    protected String criaBanco = " CREATE DATABASE  IF NOT EXISTS bancoponto;";
    protected String criaTabelaFuncoes = " CREATE TABLE funcoes ("
            + "  id int NOT NULL,"
            + "  descricao VARCHAR(50) DEFAULT NULL,"
            + "  PRIMARY KEY (`id`)"
            + "); ";

    protected String criaTabelaDepartamentos = " CREATE TABLE departamentos ("
            + "  id int NOT NULL,"
            + "  descricao VARCHAR(50) DEFAULT NULL,"
            + "  dep_n_folha VARCHAR(22) DEFAULT NULL,"
            + "  PRIMARY KEY (id)"
            + ");";

    protected String criaTabelaEmpresas = " CREATE TABLE empresas ("
            + "  id int NOT NULL,"
            + "  nome VARCHAR(150) DEFAULT NULL,"
            + "  inscricao VARCHAR(20) DEFAULT NULL,"
            + "  cnpj VARCHAR(20) DEFAULT NULL,"
            + "  endereco VARCHAR(100) DEFAULT NULL,"
            + "  bairro VARCHAR(50) DEFAULT NULL,"
            + "  cidade VARCHAR(50) DEFAULT NULL,"
            + "  cep VARCHAR(10) DEFAULT NULL,"
            + "  estado VARCHAR(2) DEFAULT NULL,"
            + "  telefone VARCHAR(20) DEFAULT NULL,"
            + "  validade_registro datetime DEFAULT NULL,"
            + "  PRIMARY KEY (id)"
            + ");";

    protected String criaTabelaFuncionarios = " CREATE TABLE funcionarios ("
            + "  id int NOT NULL,"
            + "  n_folha VARCHAR(22) DEFAULT NULL,"
            + "  nome VARCHAR(100) DEFAULT NULL,"
            + "  empresa_id int DEFAULT NULL,"
            + "  id_horario int DEFAULT NULL,"
            + "  funcao_id int DEFAULT NULL,"
            + "  departamento_id int DEFAULT NULL,"
            + "  admissao datetime DEFAULT NULL,"
            + "  demissao datetime DEFAULT NULL,"
            + "  digital tinyint(1) NOT NULL DEFAULT 0,"
            + "  endereco VARCHAR(100) DEFAULT NULL,"
            + "  bairro VARCHAR(30) DEFAULT NULL,"
            + "  cidade VARCHAR(50) DEFAULT NULL,"
            + "  uf VARCHAR(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,"
            + "  cep VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,"
            + "  telefone VARCHAR(20) DEFAULT NULL,"
            + "  cpf VARCHAR(20) DEFAULT NULL,"
            + "  nascimento datetime DEFAULT NULL,"
            + "  web_senha VARCHAR(10) DEFAULT NULL,"
            + "  banco tinyint(1) DEFAULT NULL,"
            + "  n_pis int DEFAULT NULL,"
            + "  banco_id int DEFAULT NULL,"
            + "  cnh int DEFAULT NULL,"
            + "  cat_cnh VARCHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,"
            + "  web tinyint(1) NOT NULL,"
            + "  web_email VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,"
            + "  web_nivel int DEFAULT NULL,"
            + "  PRIMARY KEY (id)"
            + "); ";

    protected String criaTabelaBatidas = " CREATE TABLE batidas ("
            + "  id int NOT NULL,"
            + "  data datetime NOT NULL,"
            + "  funcionario_id int NOT NULL,"
            + "  entrada1 VARCHAR(10) DEFAULT NULL,"
            + "  saida1 VARCHAR(10) DEFAULT NULL,"
            + "  entrada2 VARCHAR(10) DEFAULT NULL,"
            + "  saida2 VARCHAR(10) DEFAULT NULL,"
            + "  entrada3 VARCHAR(10) DEFAULT NULL,"
            + "  saida3 VARCHAR(10) DEFAULT NULL,"
            + "  ajuste VARCHAR(6) DEFAULT NULL,"
            + "  obs VARCHAR(50) DEFAULT NULL,"
            + "  horario_num int DEFAULT 0,"
            + "  PRIMARY KEY (data,funcionario_id)"
            + ");";

    protected String criaTabelaCalculos = " CREATE TABLE calculos ("
            + "  id int NOT NULL,"
            + "  data datetime NOT NULL,"
            + "  funcionario_id int NOT NULL DEFAULT 0,"
            + "  btotal int DEFAULT 0,"
            + "  bajuste int DEFAULT 0,"
            + "  bajuste_obs VARCHAR(255) DEFAULT NULL,"
            + "  extras_autorizadas int DEFAULT NULL,"
            + "  extras_ajuste int DEFAULT NULL,"
            + "  extras_ajuste2 int DEFAULT NULL,"
            + "  extras_ajuste3 int DEFAULT NULL,"
            + "  extras_banco int DEFAULT NULL,"
            + "  PRIMARY KEY (data,funcionario_id),"
            + "  UNIQUE KEY IX_id (id)"
            + "); ";

    protected String criaTabelaEquipamentos = " CREATE TABLE equipamentos ("
            + "  id int NOT NULL,"
            + "  codigo VARCHAR(10) DEFAULT NULL,"
            + "  descricao VARCHAR(50) DEFAULT NULL,"
            + "  tipo_com tinyint unsigned DEFAULT NULL,"
            + "  ip VARCHAR(30) DEFAULT NULL,"
            + "  porta_com int DEFAULT NULL,"
            + "  serial_rep VARCHAR(50) DEFAULT NULL,"
            + "  empresa_id int DEFAULT NULL,"
            + "  config VARCHAR(2000) DEFAULT NULL,"
            + "  salvar_afd_arquivo VARCHAR(1024) DEFAULT NULL,"
            + "  "
            + "  PRIMARY KEY (id)"
            +  "); ";

    protected String criaTabelaEscalas = " CREATE TABLE escalas ("
            + "  id int NOT NULL,"
            + "  descricao VARCHAR(50) DEFAULT NULL,"
            + "  tamanho int DEFAULT NULL,"
            + "  data_base datetime DEFAULT NULL,"
            + "  controlar_dsr tinyint(1) NOT NULL DEFAULT 0,"
            + "  PRIMARY KEY (id)"
            +  "); ";

    protected String criaTabelaFeriados = " CREATE TABLE feriados ("
            + "  id int NOT NULL,"
            + "  data datetime NOT NULL,"
            + "  descricao VARCHAR(50) DEFAULT NULL,"
            + "  PRIMARY KEY (id),"
            + "  UNIQUE KEY IX_data (data)"
            + ");";

    protected String criaTabelaUsuarios = " CREATE TABLE usuarios ("
            + "  id int NOT NULL,"
            + "  nome VARCHAR(20) NOT NULL,"
            + "  administrador tinyint(1) NOT NULL DEFAULT 0,"
            + "  senha VARCHAR(10) DEFAULT NULL,"
            + "  dica_senha VARCHAR(50) DEFAULT NULL,"
            + "  bloqueado tinyint(1) NOT NULL DEFAULT 0,"
            + "  desativado tinyint(1) NOT NULL DEFAULT 0,"
            + "  ultimo_login datetime DEFAULT NULL,"
            + "  permitir_alterar tinyint(1) NOT NULL DEFAULT 0,"
            + "  email VARCHAR(255) DEFAULT NULL,"
            + "  estrutura_id int DEFAULT NULL,"
            + "  permitir_dados_sensiveis tinyint(1) NOT NULL DEFAULT 0,"
            + "  aceitou_dados_sensiveis tinyint(1) NOT NULL DEFAULT 0,"
            + "  data_aut_dados_sensiveis datetime DEFAULT NULL,"
            + "  usu_aut_dados_sensiveis_id int DEFAULT NULL,"
            + "  PRIMARY KEY (id)"
            +  "); ";

    protected String criaTabelaHorarios = " CREATE TABLE horarios ("
            + "  numero int NOT NULL,"
            + "  dia_semana tinyint unsigned NOT NULL,"
            + "  nome VARCHAR(50) DEFAULT NULL,"
            + "  fechamento int DEFAULT NULL,"
            + "  minimo_extras int DEFAULT NULL,"
            + "  somar_adiantado tinyint(1) NOT NULL DEFAULT 0,"
            + "  descontar_atrasado tinyint(1) NOT NULL DEFAULT 0,"
            + "  considerar_feriados tinyint(1) NOT NULL DEFAULT 0,"
            + "  entrada1 VARCHAR(5) DEFAULT NULL,"
            + "  saida1 VARCHAR(5) DEFAULT NULL,"
            + "  entrada2 VARCHAR(5) DEFAULT NULL,"
            + "  saida2 VARCHAR(5) DEFAULT NULL,"
            + "  entrada3 VARCHAR(5) DEFAULT NULL,"
            + "  saida3 VARCHAR(5) DEFAULT NULL,"
            + "  entrada4 VARCHAR(5) DEFAULT NULL,"
            + "  saida4 VARCHAR(5) DEFAULT NULL,"
            + "  entrada5 VARCHAR(5) DEFAULT NULL,"
            + "  saida5 VARCHAR(5) DEFAULT NULL,"
            + "  t_extra VARCHAR(5) DEFAULT NULL,"
            + "  t_falta VARCHAR(5) DEFAULT NULL,"
            + "  almoco_livre tinyint(1) NOT NULL DEFAULT 0,"
            + "  compensado tinyint(1) NOT NULL DEFAULT 0,"
            + "  bh_valor int DEFAULT NULL,"
            + "  bh_percentual tinyint(1) NOT NULL DEFAULT 0,"
            + "  repetir_extras tinyint(1) NOT NULL DEFAULT 0,"
            + "  carga_diaria tinyint(1) NOT NULL DEFAULT 0,"
            + "  carga_mensal tinyint(1) NOT NULL DEFAULT 0,"
            + "  carga_semanal tinyint(1) NOT NULL DEFAULT 0,"
            + "  carga int DEFAULT NULL,"
            + "  mensalista tinyint(1) NOT NULL DEFAULT 0,"
            + "  separar_banco_horas tinyint(1) NOT NULL DEFAULT 0,"
            + "  ad_noturno_ini int DEFAULT NULL,"
            + "  ad_noturno_fim int DEFAULT NULL,"
            + "  folga tinyint(1) NOT NULL DEFAULT 0,"
            + "  PRIMARY KEY (numero,dia_semana)"
            +  "); ";

    protected String criaTabelaJustificativas = " CREATE TABLE justificativas ("
            + "  id int NOT NULL,"
            + "  nome VARCHAR(50) DEFAULT NULL,"
            + "  ajuste tinyint(1) NOT NULL DEFAULT 0,"
            + "  PRIMARY KEY (id)"
            +  "); ";

    protected String criaTabelaRegistro_sistema = " CREATE TABLE registro_sistema ("
            + "  codigo_produto int NOT NULL,"
            + "  empresa_id int NOT NULL,"
            + "  chave VARCHAR(50) DEFAULT NULL,"
            + "  PRIMARY KEY (codigo_produto,empresa_id),"
            + "  KEY IX_chave (chave)"
            +  "); ";

    protected String criaTabelaSelecao_impressao = " CREATE TABLE selecao_impressao ("
            + "  id int NOT NULL,"
            + "  coluna VARCHAR(10) DEFAULT NULL,"
            + "  tipo tinyint unsigned DEFAULT NULL,"
            + "  lista VARCHAR(15) DEFAULT NULL,"
            + "  PRIMARY KEY (id),"
            + "  KEY IX_coluna (coluna)"
            + "); ";
}
