/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.telas;

import com.Classes.Funcionario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author thayrone
 */
public class telaListaDemitidos extends javax.swing.JFrame {

    /**
     * Creates new form telaListaDemitidos
     */
    public telaListaDemitidos() {
        setSize(750, 500);
        setResizable(false);
        setLocationRelativeTo(null);
        initComponents();
        preencheTabela();
    }
    public void preencheTabela() {

        DefaultTableModel modelo = (DefaultTableModel) tabelaFuncionarios.getModel();
        modelo.setNumRows(0);
        Funcionario func = new Funcionario();
        func.listarFuncionariosDemitidos();
        for (int i = 0; i < func.ArrayFuncionario.size(); i++) {
            modelo.addRow(new Object[]{func.ArrayFuncionario.get(i).getId(), func.ArrayFuncionario.get(i).getNome(), func.ArrayFuncionario.get(i).getFolha(), func.ArrayFuncionario.get(i).getPis()});
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pTabFuncionariosDemitidos = new javax.swing.JScrollPane();
        tabelaFuncionarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pTitulo.setBackground(new java.awt.Color(0, 102, 153));

        lblTitulo.setBackground(new java.awt.Color(0, 102, 153));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cartão-de-identificação-64.png"))); // NOI18N
        lblTitulo.setText("Lista de funcionários demitidos");

        javax.swing.GroupLayout pTituloLayout = new javax.swing.GroupLayout(pTitulo);
        pTitulo.setLayout(pTituloLayout);
        pTituloLayout.setHorizontalGroup(
            pTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pTituloLayout.setVerticalGroup(
            pTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(pTitulo, java.awt.BorderLayout.NORTH);

        tabelaFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#ID", "Nome", "Nº Folha", "Nº Pis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pTabFuncionariosDemitidos.setViewportView(tabelaFuncionarios);
        if (tabelaFuncionarios.getColumnModel().getColumnCount() > 0) {
            tabelaFuncionarios.getColumnModel().getColumn(0).setMinWidth(30);
            tabelaFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabelaFuncionarios.getColumnModel().getColumn(0).setMaxWidth(30);
            tabelaFuncionarios.getColumnModel().getColumn(1).setMinWidth(320);
            tabelaFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(320);
            tabelaFuncionarios.getColumnModel().getColumn(1).setMaxWidth(320);
            tabelaFuncionarios.getColumnModel().getColumn(2).setMinWidth(100);
            tabelaFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(100);
            tabelaFuncionarios.getColumnModel().getColumn(2).setMaxWidth(100);
            tabelaFuncionarios.getColumnModel().getColumn(3).setMinWidth(150);
            tabelaFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(150);
            tabelaFuncionarios.getColumnModel().getColumn(3).setMaxWidth(150);
        }
        if (tabelaFuncionarios.getColumnModel().getColumnCount() > 0) {
            tabelaFuncionarios.getColumnModel().getColumn(0).setMinWidth(30);
            tabelaFuncionarios.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabelaFuncionarios.getColumnModel().getColumn(0).setMaxWidth(30);
            tabelaFuncionarios.getColumnModel().getColumn(1).setMinWidth(320);
            tabelaFuncionarios.getColumnModel().getColumn(1).setPreferredWidth(320);
            tabelaFuncionarios.getColumnModel().getColumn(1).setMaxWidth(320);
            tabelaFuncionarios.getColumnModel().getColumn(2).setMinWidth(80);
            tabelaFuncionarios.getColumnModel().getColumn(2).setPreferredWidth(80);
            tabelaFuncionarios.getColumnModel().getColumn(2).setMaxWidth(80);
            tabelaFuncionarios.getColumnModel().getColumn(3).setMinWidth(150);
            tabelaFuncionarios.getColumnModel().getColumn(3).setPreferredWidth(150);
            tabelaFuncionarios.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        getContentPane().add(pTabFuncionariosDemitidos, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaListaDemitidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaListaDemitidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaListaDemitidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaListaDemitidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaListaDemitidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane pTabFuncionariosDemitidos;
    private javax.swing.JPanel pTitulo;
    private javax.swing.JTable tabelaFuncionarios;
    // End of variables declaration//GEN-END:variables
}
