/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.telas;

import com.Classes.Departamento;
import com.Classes.Empresa;
import com.Classes.Funcao;
import com.Classes.Funcionario;
import com.Classes.Horario;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author thayrone
 */
public class telaCadFuncionarios extends javax.swing.JFrame {

    public int id_recebido;

    /**
     * Creates new form telaCadFuncionarios
     */
    public telaCadFuncionarios(int id_funcionario) {
        setSize(800, 600);
        setResizable(false);
        setLocationRelativeTo(null);
        System.out.println("O id recebido foi: " + id_funcionario);
        initComponents();
        id_recebido = id_funcionario;
        preencheComboEmpresa();
        preencheComboHorario();
        preenche();

    }

    private void preenche() {

        if (id_recebido != 0) {

            int index = Funcionario.localizaIdex(id_recebido);
            System.out.println("O index localizado foi: " + index);
            tbNome.setText(Funcionario.ArrayFuncionario.get(index).getNome());
            tbFolha.setText(Integer.toString(Funcionario.ArrayFuncionario.get(index).getFolha()));
            tbPis.setText(Funcionario.ArrayFuncionario.get(index).getPis());
            int empresaID = Funcionario.ArrayFuncionario.get(index).getEmpresa_id();
            int indexEmpresa = empresaID - 1;
            cbEmpresa.setSelectedIndex(indexEmpresa);
            int HorarioID = Funcionario.ArrayFuncionario.get(index).getId_horario();
            int indexHorario = HorarioID - 1;
            cbHorario.setSelectedIndex(indexHorario);
            
            int FuncaoID = Integer.parseInt(Funcionario.ArrayFuncionario.get(index).getFuncao());
            int indexFuncao = Funcao.localizaIdex(FuncaoID);
            cbFuncao.setSelectedIndex(indexFuncao);

            int DepartamentoID = Integer.parseInt(Funcionario.ArrayFuncionario.get(index).getDepartamento());
            int indexDepartamento = Departamento.localizaIdex(DepartamentoID);
            cbDepartamento.setSelectedIndex(indexDepartamento);

            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String AdmissaoFormatada = dateFormat.format(Funcionario.ArrayFuncionario.get(index).getAdmissao());
            tbAdmissao.setText(AdmissaoFormatada);
            if (Funcionario.ArrayFuncionario.get(index).getDemissao() != null) {
                String DemissaoFormatada = dateFormat.format(Funcionario.ArrayFuncionario.get(index).getDemissao());
                tbDemissao.setText(DemissaoFormatada);
            }
        }

    }

    private void preencheComboEmpresa() {

        DefaultComboBoxModel modeloCEmpresa = new DefaultComboBoxModel(Empresa.ArrayNomesEmpresa.toArray());
        cbEmpresa.setModel(modeloCEmpresa);
    }

    private void preencheComboHorario() {

        DefaultComboBoxModel modeloCHorario = new DefaultComboBoxModel(Horario.ArrayNomesHorario.toArray());
        cbHorario.setModel(modeloCHorario);
    }

    private void preencheComboDepartamento() {

        DefaultComboBoxModel modeloCDepartamento = new DefaultComboBoxModel(Departamento.ArrayNomesDepartamento.toArray());
        cbDepartamento.setModel(modeloCDepartamento);
    }

    private void preencheComboFuncao() {

        DefaultComboBoxModel modeloCFuncao = new DefaultComboBoxModel(Funcao.ArrayNomesFuncao.toArray());
        cbFuncao.setModel(modeloCFuncao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        painelPrincipal = new javax.swing.JPanel();
        painelDadosPrincipais = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        tbNome = new javax.swing.JTextField();
        lblFolha = new javax.swing.JLabel();
        tbFolha = new javax.swing.JTextField();
        lblPis = new javax.swing.JLabel();
        tbPis = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabPrincipal = new javax.swing.JPanel();
        lblHorario = new javax.swing.JLabel();
        lblFuncao = new javax.swing.JLabel();
        lblDepartamento = new javax.swing.JLabel();
        lblEmpresa = new javax.swing.JLabel();
        cbEmpresa = new javax.swing.JComboBox<>();
        cbHorario = new javax.swing.JComboBox<>();
        lblAdmissao = new javax.swing.JLabel();
        lblDemissao = new javax.swing.JLabel();
        tbAdmissao = new javax.swing.JFormattedTextField();
        tbDemissao = new javax.swing.JFormattedTextField();
        cbFuncao = new javax.swing.JComboBox<>();
        cbDepartamento = new javax.swing.JComboBox<>();
        tabAdicionais = new javax.swing.JPanel();
        lblEndereco = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        lblCnh = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        tbEndereco = new javax.swing.JTextField();
        tbBairro = new javax.swing.JTextField();
        tbCidade = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        tbCep = new javax.swing.JFormattedTextField();
        tbTelefone = new javax.swing.JFormattedTextField();
        tbCpf = new javax.swing.JFormattedTextField();
        tbNascimento = new javax.swing.JFormattedTextField();
        tbCnh = new javax.swing.JTextField();
        cbCategoria = new javax.swing.JComboBox<>();
        tabBancoDeHoras = new javax.swing.JPanel();
        checkHabilitaBanco = new javax.swing.JCheckBox();
        lblDataInicio = new javax.swing.JLabel();
        tbDataInicio = new javax.swing.JFormattedTextField();
        tbDataFim = new javax.swing.JFormattedTextField();
        lblDataFim = new javax.swing.JLabel();
        lblCredito = new javax.swing.JLabel();
        cbCredito = new javax.swing.JComboBox<>();
        lblDebito = new javax.swing.JLabel();
        cbDebito = new javax.swing.JComboBox<>();
        checkZerar = new javax.swing.JCheckBox();
        sPeriodoZerar = new javax.swing.JSpinner();
        lblMes = new javax.swing.JLabel();
        checkCopiar = new javax.swing.JCheckBox();
        checkNaoDescontar = new javax.swing.JCheckBox();
        cbCopiar = new javax.swing.JComboBox<>();
        btnConfiguracaoEspecial = new javax.swing.JButton();
        tabAfastamentos = new javax.swing.JPanel();
        btnNovoAfastamento = new javax.swing.JButton();
        btnAlterarAfastamento = new javax.swing.JButton();
        btnExcluirAfastamento = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listAfastamento = new javax.swing.JList<>();
        tabWeb = new javax.swing.JPanel();
        checkHabilitaWeb = new javax.swing.JCheckBox();
        lblEmail = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        tbEmail = new javax.swing.JTextField();
        lblNivel = new javax.swing.JLabel();
        cbNivelWeb = new javax.swing.JComboBox<>();
        tbSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelTitulo.setBackground(new java.awt.Color(0, 102, 153));

        lblTitulo.setBackground(new java.awt.Color(0, 102, 153));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cartão-de-identificação-64.png"))); // NOI18N
        lblTitulo.setText("Cadastro de funcionários");

        btnSalvar.setBackground(new java.awt.Color(0, 102, 153));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(painelTitulo, java.awt.BorderLayout.NORTH);

        painelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNome.setText("Nome:");
        lblNome.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tbNome.setMaximumSize(new java.awt.Dimension(300, 22));
        tbNome.setMinimumSize(new java.awt.Dimension(300, 22));
        tbNome.setPreferredSize(new java.awt.Dimension(300, 22));
        tbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNomeActionPerformed(evt);
            }
        });

        lblFolha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFolha.setText("Nº Folha:");

        tbFolha.setMinimumSize(new java.awt.Dimension(300, 22));
        tbFolha.setPreferredSize(new java.awt.Dimension(300, 22));

        lblPis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPis.setText("Nº PIS:");

        tbPis.setMinimumSize(new java.awt.Dimension(300, 22));
        tbPis.setPreferredSize(new java.awt.Dimension(300, 22));
        tbPis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbPisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelDadosPrincipaisLayout = new javax.swing.GroupLayout(painelDadosPrincipais);
        painelDadosPrincipais.setLayout(painelDadosPrincipaisLayout);
        painelDadosPrincipaisLayout.setHorizontalGroup(
            painelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPrincipaisLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(painelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblFolha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblPis))
                .addGap(24, 24, 24)
                .addGroup(painelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tbPis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(tbFolha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDadosPrincipaisLayout.setVerticalGroup(
            painelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPrincipaisLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(painelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbFolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFolha))
                .addGap(18, 18, 18)
                .addGroup(painelDadosPrincipaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbPis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPis)))
        );

        painelPrincipal.add(painelDadosPrincipais, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 460, 150));

        getContentPane().add(painelPrincipal, java.awt.BorderLayout.CENTER);

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 153));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        lblHorario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHorario.setText("Horário:");
        lblHorario.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblFuncao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncao.setText("Função:");

        lblDepartamento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDepartamento.setText("Departamento:");

        lblEmpresa.setText("Empresa:");

        cbEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblAdmissao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdmissao.setText("Admissão:");

        lblDemissao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDemissao.setText("Demissão");

        tbAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        cbFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFuncaoActionPerformed(evt);
            }
        });

        cbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout tabPrincipalLayout = new javax.swing.GroupLayout(tabPrincipal);
        tabPrincipal.setLayout(tabPrincipalLayout);
        tabPrincipalLayout.setHorizontalGroup(
            tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDemissao)
                    .addComponent(lblAdmissao)
                    .addComponent(lblHorario)
                    .addComponent(lblEmpresa)
                    .addComponent(lblFuncao)
                    .addComponent(lblDepartamento))
                .addGap(30, 30, 30)
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbHorario, javax.swing.GroupLayout.Alignment.TRAILING, 0, 414, Short.MAX_VALUE)
                    .addComponent(cbEmpresa, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tbDemissao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(tbAdmissao, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(cbFuncao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        tabPrincipalLayout.setVerticalGroup(
            tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPrincipalLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpresa)
                    .addComponent(cbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncao)
                    .addComponent(cbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartamento)
                    .addComponent(cbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdmissao)
                    .addComponent(tbAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDemissao)
                    .addComponent(tbDemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Principal", tabPrincipal);

        tabAdicionais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lblEndereco.setText("Endereço:");

        lblCidade.setText("Cidade:");

        lblBairro.setText("Bairro:");

        lblCep.setText("CEP:");

        lblEstado.setText("Estado:");

        lblTelefone.setText("Telefone:");

        lblCpf.setText("CPF:");

        lblNascimento.setText("Nascimento:");

        lblCnh.setText("CNH:");

        lblCategoria.setText("Categoria:");

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        try {
            tbCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "A", "B", "C", "D", "E", " " }));

        javax.swing.GroupLayout tabAdicionaisLayout = new javax.swing.GroupLayout(tabAdicionais);
        tabAdicionais.setLayout(tabAdicionaisLayout);
        tabAdicionaisLayout.setHorizontalGroup(
            tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAdicionaisLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCnh)
                    .addComponent(lblBairro)
                    .addComponent(lblCep)
                    .addComponent(lblTelefone)
                    .addComponent(lblCpf)
                    .addComponent(lblNascimento)
                    .addComponent(lblEndereco))
                .addGap(18, 18, 18)
                .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAdicionaisLayout.createSequentialGroup()
                        .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(tabAdicionaisLayout.createSequentialGroup()
                                    .addComponent(tbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblCidade)
                                    .addGap(18, 18, 18)
                                    .addComponent(tbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblEstado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbEstado, 0, 1, Short.MAX_VALUE))
                                .addComponent(tbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tbCep, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tbCpf, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tbNascimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(tabAdicionaisLayout.createSequentialGroup()
                        .addComponent(tbCnh, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(344, 344, 344))))
        );
        tabAdicionaisLayout.setVerticalGroup(
            tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAdicionaisLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndereco)
                    .addComponent(tbEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBairro)
                    .addComponent(lblCidade)
                    .addComponent(lblEstado)
                    .addComponent(tbBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCep)
                    .addComponent(tbCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(tbTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(tbCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascimento)
                    .addComponent(tbNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabAdicionaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCnh)
                    .addComponent(tbCnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Dados Adicionais", tabAdicionais);

        tabBancoDeHoras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        checkHabilitaBanco.setText("Habilitar banco de horas");

        lblDataInicio.setText("Data inicial:");

        lblDataFim.setText("Data final:");

        lblCredito.setText("Totalizadores de credito:");

        cbCredito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas as horas extras.", "Somente a 1º feixa de extra", "Nenhuma hora extra", "Configuração especial" }));

        lblDebito.setText("Totalizadores de debito:");

        cbDebito.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas as horas faltosas", "Nenhuma hora faltosa" }));

        checkZerar.setText("Zerar saldo acumulado a cada");

        sPeriodoZerar.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        lblMes.setText("meses.");

        checkCopiar.setText("Copiar configurações de:");

        checkNaoDescontar.setText("Não descontar horas do banco em caso de FALTA.");

        cbCopiar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Padrão", "Funcionario 1", "Funcionario 2", "Funcionario 3" }));

        btnConfiguracaoEspecial.setText("Configurações especiais");

        javax.swing.GroupLayout tabBancoDeHorasLayout = new javax.swing.GroupLayout(tabBancoDeHoras);
        tabBancoDeHoras.setLayout(tabBancoDeHorasLayout);
        tabBancoDeHorasLayout.setHorizontalGroup(
            tabBancoDeHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBancoDeHorasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabBancoDeHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabBancoDeHorasLayout.createSequentialGroup()
                        .addGroup(tabBancoDeHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkHabilitaBanco)
                            .addGroup(tabBancoDeHorasLayout.createSequentialGroup()
                                .addComponent(lblDataInicio)
                                .addGap(18, 18, 18)
                                .addComponent(tbDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(lblDataFim)
                        .addGap(18, 18, 18)
                        .addComponent(tbDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabBancoDeHorasLayout.createSequentialGroup()
                        .addGroup(tabBancoDeHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabBancoDeHorasLayout.createSequentialGroup()
                                .addComponent(lblDebito)
                                .addGap(21, 21, 21)
                                .addComponent(cbDebito, 0, 1, Short.MAX_VALUE))
                            .addGroup(tabBancoDeHorasLayout.createSequentialGroup()
                                .addComponent(lblCredito)
                                .addGap(18, 18, 18)
                                .addComponent(cbCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnConfiguracaoEspecial))
                    .addComponent(checkNaoDescontar)
                    .addGroup(tabBancoDeHorasLayout.createSequentialGroup()
                        .addComponent(checkCopiar)
                        .addGap(18, 18, 18)
                        .addComponent(cbCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabBancoDeHorasLayout.createSequentialGroup()
                        .addComponent(checkZerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sPeriodoZerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMes)))
                .addContainerGap())
        );
        tabBancoDeHorasLayout.setVerticalGroup(
            tabBancoDeHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabBancoDeHorasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(checkHabilitaBanco)
                .addGap(18, 18, 18)
                .addGroup(tabBancoDeHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataInicio)
                    .addComponent(tbDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataFim)
                    .addComponent(tbDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabBancoDeHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCredito)
                    .addComponent(cbCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfiguracaoEspecial))
                .addGap(18, 18, 18)
                .addGroup(tabBancoDeHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDebito)
                    .addComponent(cbDebito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabBancoDeHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkZerar)
                    .addComponent(sPeriodoZerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMes))
                .addGap(18, 18, 18)
                .addComponent(checkNaoDescontar)
                .addGap(18, 18, 18)
                .addGroup(tabBancoDeHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkCopiar)
                    .addComponent(cbCopiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Banco de horas", tabBancoDeHoras);

        btnNovoAfastamento.setText("Novo");

        btnAlterarAfastamento.setText("Alterar");

        btnExcluirAfastamento.setText("Excluir");
        btnExcluirAfastamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAfastamentoActionPerformed(evt);
            }
        });

        listAfastamento.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listAfastamento);

        javax.swing.GroupLayout tabAfastamentosLayout = new javax.swing.GroupLayout(tabAfastamentos);
        tabAfastamentos.setLayout(tabAfastamentosLayout);
        tabAfastamentosLayout.setHorizontalGroup(
            tabAfastamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAfastamentosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabAfastamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterarAfastamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNovoAfastamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirAfastamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        tabAfastamentosLayout.setVerticalGroup(
            tabAfastamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAfastamentosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabAfastamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tabAfastamentosLayout.createSequentialGroup()
                        .addComponent(btnNovoAfastamento)
                        .addGap(18, 18, 18)
                        .addComponent(btnAlterarAfastamento)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirAfastamento)))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Afastamentos e Férias", tabAfastamentos);

        checkHabilitaWeb.setText("Habilitar ponto Web");

        lblEmail.setText("E-mail:");

        lblSenha.setText("Senha:");

        lblNivel.setText("Nivel de Permissão:");

        cbNivelWeb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout tabWebLayout = new javax.swing.GroupLayout(tabWeb);
        tabWeb.setLayout(tabWebLayout);
        tabWebLayout.setHorizontalGroup(
            tabWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabWebLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(tabWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabWebLayout.createSequentialGroup()
                        .addGroup(tabWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEmail)
                            .addComponent(lblSenha))
                        .addGap(18, 18, 18)
                        .addGroup(tabWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(checkHabilitaWeb)
                    .addGroup(tabWebLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lblNivel)
                        .addGap(18, 18, 18)
                        .addComponent(cbNivelWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tabWebLayout.setVerticalGroup(
            tabWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabWebLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(checkHabilitaWeb)
                .addGap(18, 18, 18)
                .addGroup(tabWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(tbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(tabWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(tbSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabWebLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNivelWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNivel))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Dados Web", tabWeb);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNomeActionPerformed

    private void tbPisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbPisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbPisActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirAfastamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAfastamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExcluirAfastamentoActionPerformed

    private void cbFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFuncaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadFuncionarios(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarAfastamento;
    private javax.swing.JButton btnConfiguracaoEspecial;
    private javax.swing.JButton btnExcluirAfastamento;
    private javax.swing.JButton btnNovoAfastamento;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbCopiar;
    private javax.swing.JComboBox<String> cbCredito;
    private javax.swing.JComboBox<String> cbDebito;
    private javax.swing.JComboBox<String> cbDepartamento;
    private javax.swing.JComboBox<String> cbEmpresa;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbFuncao;
    private javax.swing.JComboBox<String> cbHorario;
    private javax.swing.JComboBox<String> cbNivelWeb;
    private javax.swing.JCheckBox checkCopiar;
    private javax.swing.JCheckBox checkHabilitaBanco;
    private javax.swing.JCheckBox checkHabilitaWeb;
    private javax.swing.JCheckBox checkNaoDescontar;
    private javax.swing.JCheckBox checkZerar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAdmissao;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCnh;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCredito;
    private javax.swing.JLabel lblDataFim;
    private javax.swing.JLabel lblDataInicio;
    private javax.swing.JLabel lblDebito;
    private javax.swing.JLabel lblDemissao;
    private javax.swing.JLabel lblDepartamento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpresa;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFolha;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPis;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> listAfastamento;
    private javax.swing.JPanel painelDadosPrincipais;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JSpinner sPeriodoZerar;
    private javax.swing.JPanel tabAdicionais;
    private javax.swing.JPanel tabAfastamentos;
    private javax.swing.JPanel tabBancoDeHoras;
    private javax.swing.JPanel tabPrincipal;
    private javax.swing.JPanel tabWeb;
    private javax.swing.JFormattedTextField tbAdmissao;
    private javax.swing.JTextField tbBairro;
    private javax.swing.JFormattedTextField tbCep;
    private javax.swing.JTextField tbCidade;
    private javax.swing.JTextField tbCnh;
    private javax.swing.JFormattedTextField tbCpf;
    private javax.swing.JFormattedTextField tbDataFim;
    private javax.swing.JFormattedTextField tbDataInicio;
    private javax.swing.JFormattedTextField tbDemissao;
    private javax.swing.JTextField tbEmail;
    private javax.swing.JTextField tbEndereco;
    private javax.swing.JTextField tbFolha;
    private javax.swing.JFormattedTextField tbNascimento;
    private javax.swing.JTextField tbNome;
    private javax.swing.JTextField tbPis;
    private javax.swing.JPasswordField tbSenha;
    private javax.swing.JFormattedTextField tbTelefone;
    // End of variables declaration//GEN-END:variables
}
