package com;

import com.Classes.Departamento;
import com.Classes.Empresa;
import com.Classes.Funcao;
import com.Classes.Funcionario;
import static com.Classes.Funcionario.ArrayFuncionario;
import com.Classes.Horario;
import com.dados.comandosBanco;
import com.formdev.flatlaf.FlatLightLaf;
import com.telas.telaCadFuncionarios;
import com.telas.telaListaFuncionarios;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author thayrone
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);

        Empresa.listarEmpresas();
        Horario.listarHorarios();
        Departamento.listarDepartamentos();
        Funcao.listarFuncoes();
        
        
    }

    public void atualizaPainel() {

        Funcionario func = new Funcionario();

        contTotal.setText(Integer.toString(func.contarIdFuncionario()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenu = new javax.swing.JPanel();
        btnFuncionarios = new javax.swing.JButton();
        btnHorarios = new javax.swing.JButton();
        btnEscalas = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        btnComunicacao = new javax.swing.JButton();
        btnCalculos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        TabelasInicio = new javax.swing.JTabbedPane();
        pContFuncionarios = new javax.swing.JPanel();
        contTotal = new javax.swing.JLabel();
        contPresentes = new javax.swing.JLabel();
        contAusentes = new javax.swing.JLabel();
        contAfastados = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblPresentes = new javax.swing.JLabel();
        lblAuxentes = new javax.swing.JLabel();
        lblAfastados = new javax.swing.JLabel();
        pEspacador = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        cadUsuarios = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        cadEmpresa = new javax.swing.JMenuItem();
        cadFuncionarios = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        cadHorarios = new javax.swing.JMenuItem();
        cadEscalas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        cadJustificativas = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        cadTabelaFeriados = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        cadCargos = new javax.swing.JMenuItem();
        cadDepartamentos = new javax.swing.JMenuItem();
        cadCentroCusto = new javax.swing.JMenuItem();
        menuComunicacao = new javax.swing.JMenu();
        comRecebeAFD = new javax.swing.JMenuItem();
        comEnviarReceber = new javax.swing.JMenuItem();
        menuManutencao = new javax.swing.JMenu();
        manEquipamentos = new javax.swing.JMenuItem();
        manServicosOnline = new javax.swing.JMenuItem();
        manBanco = new javax.swing.JMenuItem();
        manConfiguracoes = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        relCartaoPonto = new javax.swing.JMenuItem();
        relFiscais = new javax.swing.JMenu();
        relACJEF = new javax.swing.JMenuItem();
        relAFDT = new javax.swing.JMenuItem();
        relFuncionarios = new javax.swing.JMenu();
        relAtivos = new javax.swing.JMenuItem();
        relDemitidos = new javax.swing.JMenuItem();
        relBanco = new javax.swing.JMenuItem();
        relHorarios = new javax.swing.JMenuItem();
        relEscalas = new javax.swing.JMenuItem();
        relAbsenteismo = new javax.swing.JMenuItem();
        relAfastamentos = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        ajuManuais = new javax.swing.JMenuItem();
        ajuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        pMenu.setBackground(new java.awt.Color(0, 102, 153));

        btnFuncionarios.setBackground(new java.awt.Color(0, 102, 153));
        btnFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        btnFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cartão-de-identificação-64.png"))); // NOI18N
        btnFuncionarios.setText("Funcionários");
        btnFuncionarios.setToolTipText("Cadastro de funcionários");
        btnFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFuncionarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFuncionarios.setMaximumSize(new java.awt.Dimension(80, 80));
        btnFuncionarios.setMinimumSize(new java.awt.Dimension(80, 80));
        btnFuncionarios.setPreferredSize(new java.awt.Dimension(131, 105));
        btnFuncionarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFuncionariosActionPerformed(evt);
            }
        });

        btnHorarios.setBackground(new java.awt.Color(0, 102, 153));
        btnHorarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnHorarios.setForeground(new java.awt.Color(255, 255, 255));
        btnHorarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-hora-extra-64.png"))); // NOI18N
        btnHorarios.setText("Horários");
        btnHorarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHorarios.setMaximumSize(new java.awt.Dimension(80, 80));
        btnHorarios.setMinimumSize(new java.awt.Dimension(131, 105));
        btnHorarios.setPreferredSize(new java.awt.Dimension(131, 105));
        btnHorarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnEscalas.setBackground(new java.awt.Color(0, 102, 153));
        btnEscalas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEscalas.setForeground(new java.awt.Color(255, 255, 255));
        btnEscalas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-ciclo-de-vida-64.png"))); // NOI18N
        btnEscalas.setText("Escalas");
        btnEscalas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEscalas.setMaximumSize(new java.awt.Dimension(80, 80));
        btnEscalas.setMinimumSize(new java.awt.Dimension(80, 80));
        btnEscalas.setPreferredSize(new java.awt.Dimension(80, 80));
        btnEscalas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEscalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscalasActionPerformed(evt);
            }
        });

        Logo.setBackground(new java.awt.Color(0, 153, 153));
        Logo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        Logo.setText("Ponto");

        btnComunicacao.setBackground(new java.awt.Color(0, 102, 153));
        btnComunicacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnComunicacao.setForeground(new java.awt.Color(255, 255, 255));
        btnComunicacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-setas-ordenadas-64.png"))); // NOI18N
        btnComunicacao.setText("Comunicação");
        btnComunicacao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnComunicacao.setMaximumSize(new java.awt.Dimension(80, 80));
        btnComunicacao.setMinimumSize(new java.awt.Dimension(80, 80));
        btnComunicacao.setPreferredSize(new java.awt.Dimension(80, 80));
        btnComunicacao.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnComunicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComunicacaoActionPerformed(evt);
            }
        });

        btnCalculos.setBackground(new java.awt.Color(0, 102, 153));
        btnCalculos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCalculos.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-contabilidade-64.png"))); // NOI18N
        btnCalculos.setText("Calculos");
        btnCalculos.setActionCommand("");
        btnCalculos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCalculos.setMaximumSize(new java.awt.Dimension(80, 80));
        btnCalculos.setMinimumSize(new java.awt.Dimension(80, 80));
        btnCalculos.setPreferredSize(new java.awt.Dimension(80, 80));
        btnCalculos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCalculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculosActionPerformed(evt);
            }
        });

        btnSair.setBackground(new java.awt.Color(0, 102, 153));
        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-sair-64.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setActionCommand("");
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setMaximumSize(new java.awt.Dimension(80, 80));
        btnSair.setMinimumSize(new java.awt.Dimension(80, 80));
        btnSair.setPreferredSize(new java.awt.Dimension(80, 80));
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnComunicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCalculos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMenuLayout.setVerticalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCalculos, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnComunicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEscalas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Logo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pMenu, java.awt.BorderLayout.NORTH);

        TabelasInicio.setBackground(new java.awt.Color(0, 102, 153));
        TabelasInicio.setForeground(new java.awt.Color(255, 255, 255));
        TabelasInicio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        pContFuncionarios.setMaximumSize(new java.awt.Dimension(500, 200));
        pContFuncionarios.setMinimumSize(new java.awt.Dimension(500, 200));
        pContFuncionarios.setPreferredSize(new java.awt.Dimension(500, 200));
        pContFuncionarios.setLayout(new java.awt.GridLayout(2, 0));

        contTotal.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        contTotal.setForeground(new java.awt.Color(0, 0, 0));
        contTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contTotal.setText("0");
        contTotal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pContFuncionarios.add(contTotal);

        contPresentes.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        contPresentes.setForeground(new java.awt.Color(0, 0, 0));
        contPresentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contPresentes.setText("0");
        pContFuncionarios.add(contPresentes);

        contAusentes.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        contAusentes.setForeground(new java.awt.Color(0, 0, 0));
        contAusentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contAusentes.setText("0");
        pContFuncionarios.add(contAusentes);

        contAfastados.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        contAfastados.setForeground(new java.awt.Color(0, 0, 0));
        contAfastados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contAfastados.setText("0");
        pContFuncionarios.add(contAfastados);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("Total");
        pContFuncionarios.add(lblTotal);

        lblPresentes.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblPresentes.setForeground(new java.awt.Color(0, 0, 0));
        lblPresentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPresentes.setText("Presentes");
        pContFuncionarios.add(lblPresentes);

        lblAuxentes.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblAuxentes.setForeground(new java.awt.Color(0, 0, 0));
        lblAuxentes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAuxentes.setText("Ausentes");
        pContFuncionarios.add(lblAuxentes);

        lblAfastados.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblAfastados.setForeground(new java.awt.Color(0, 0, 0));
        lblAfastados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAfastados.setText("Afastados");
        pContFuncionarios.add(lblAfastados);

        TabelasInicio.addTab("Funcionários", new javax.swing.ImageIcon(getClass().getResource("/icons8-cartão-de-identificação-64.png")), pContFuncionarios); // NOI18N

        getContentPane().add(TabelasInicio, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pEspacadorLayout = new javax.swing.GroupLayout(pEspacador);
        pEspacador.setLayout(pEspacadorLayout);
        pEspacadorLayout.setHorizontalGroup(
            pEspacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1736, Short.MAX_VALUE)
        );
        pEspacadorLayout.setVerticalGroup(
            pEspacadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        getContentPane().add(pEspacador, java.awt.BorderLayout.PAGE_END);

        menuCadastros.setText("Cadastros");

        cadUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cadUsuarios.setText("Usuários");
        cadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadUsuariosActionPerformed(evt);
            }
        });
        menuCadastros.add(cadUsuarios);
        menuCadastros.add(jSeparator1);

        cadEmpresa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cadEmpresa.setText("Empresa");
        cadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadEmpresaActionPerformed(evt);
            }
        });
        menuCadastros.add(cadEmpresa);

        cadFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cadFuncionarios.setText("Funcionários");
        cadFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncionariosActionPerformed(evt);
            }
        });
        menuCadastros.add(cadFuncionarios);
        menuCadastros.add(jSeparator2);

        cadHorarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cadHorarios.setText("Horários");
        cadHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadHorariosActionPerformed(evt);
            }
        });
        menuCadastros.add(cadHorarios);

        cadEscalas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cadEscalas.setText("Escalas");
        menuCadastros.add(cadEscalas);
        menuCadastros.add(jSeparator3);

        cadJustificativas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cadJustificativas.setText("Justificativas");
        menuCadastros.add(cadJustificativas);
        menuCadastros.add(jSeparator4);

        cadTabelaFeriados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cadTabelaFeriados.setText("Tabelas de feriados");
        menuCadastros.add(cadTabelaFeriados);
        menuCadastros.add(jSeparator5);

        cadCargos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cadCargos.setText("Cargos");
        menuCadastros.add(cadCargos);

        cadDepartamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        cadDepartamentos.setText("Departamentos");
        menuCadastros.add(cadDepartamentos);

        cadCentroCusto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        cadCentroCusto.setText("Centros de custo");
        menuCadastros.add(cadCentroCusto);

        menu.add(menuCadastros);

        menuComunicacao.setText("Comunicação");

        comRecebeAFD.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        comRecebeAFD.setText("Receber de arquivo AFD");
        comRecebeAFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comRecebeAFDActionPerformed(evt);
            }
        });
        menuComunicacao.add(comRecebeAFD);

        comEnviarReceber.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        comEnviarReceber.setText("Enviar e Receber");
        menuComunicacao.add(comEnviarReceber);

        menu.add(menuComunicacao);

        menuManutencao.setText("Manutenção");

        manEquipamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        manEquipamentos.setText("Equipamentos");
        menuManutencao.add(manEquipamentos);

        manServicosOnline.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        manServicosOnline.setText("Serviços online");
        menuManutencao.add(manServicosOnline);

        manBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        manBanco.setText("Banco de dados");
        menuManutencao.add(manBanco);

        manConfiguracoes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        manConfiguracoes.setText("Configurações");
        menuManutencao.add(manConfiguracoes);

        menu.add(menuManutencao);

        menuRelatorios.setText("Relatórios");

        relCartaoPonto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        relCartaoPonto.setText("Cartão de ponto");
        menuRelatorios.add(relCartaoPonto);

        relFiscais.setText("Fiscais");

        relACJEF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        relACJEF.setText("ACJEF");
        relFiscais.add(relACJEF);

        relAFDT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        relAFDT.setText("AFDT");
        relFiscais.add(relAFDT);

        menuRelatorios.add(relFiscais);

        relFuncionarios.setText("Funcionários");

        relAtivos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        relAtivos.setText("Ativos");
        relFuncionarios.add(relAtivos);

        relDemitidos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        relDemitidos.setText("Demitidos");
        relFuncionarios.add(relDemitidos);

        menuRelatorios.add(relFuncionarios);

        relBanco.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        relBanco.setText("Banco de horas");
        menuRelatorios.add(relBanco);

        relHorarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        relHorarios.setText("Horários");
        menuRelatorios.add(relHorarios);

        relEscalas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        relEscalas.setText("Escalas");
        menuRelatorios.add(relEscalas);

        relAbsenteismo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        relAbsenteismo.setText("Absenteísmo");
        menuRelatorios.add(relAbsenteismo);

        relAfastamentos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        relAfastamentos.setText("Afastamentos");
        menuRelatorios.add(relAfastamentos);

        menu.add(menuRelatorios);

        menuAjuda.setText("Ajuda");

        ajuManuais.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ajuManuais.setText("Manuais");
        menuAjuda.add(ajuManuais);

        ajuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ajuSobre.setText("Sobre o sistema");
        ajuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(ajuSobre);

        menu.add(menuAjuda);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadUsuariosActionPerformed
        // TODO add your handling code here:
        Icon figura = new ImageIcon(getToolkit().createImage(getClass().getResource("/selecionado.png")));
        JOptionPane.showMessageDialog(null, "Ocorreu um erro no cadastro", "Atenção!", JOptionPane.PLAIN_MESSAGE, figura);


    }//GEN-LAST:event_cadUsuariosActionPerformed

    private void cadFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncionariosActionPerformed
        // TODO add your handling code here:
        telaListaFuncionarios listaFuncionarios = new telaListaFuncionarios();
        listaFuncionarios.setVisible(true);
    }//GEN-LAST:event_cadFuncionariosActionPerformed

    private void cadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadEmpresaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cadEmpresaActionPerformed

    private void cadHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadHorariosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cadHorariosActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        atualizaPainel();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnEscalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEscalasActionPerformed

    private void comRecebeAFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comRecebeAFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comRecebeAFDActionPerformed

    private void ajuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajuSobreActionPerformed
        // TODO add your handling code here:
        Icon figura = new ImageIcon(getToolkit().createImage(getClass().getResource("/info.png")));
        JOptionPane.showMessageDialog(null, "Versão 0.0.1", "Versão", JOptionPane.PLAIN_MESSAGE, figura);
    }//GEN-LAST:event_ajuSobreActionPerformed

    private void btnComunicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComunicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComunicacaoActionPerformed

    private void btnCalculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFuncionariosActionPerformed
        // TODO add your handling code here:
        telaListaFuncionarios listaFuncionarios = new telaListaFuncionarios();
        listaFuncionarios.setVisible(true);
    }//GEN-LAST:event_btnFuncionariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatLightLaf");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JTabbedPane TabelasInicio;
    private javax.swing.JMenuItem ajuManuais;
    private javax.swing.JMenuItem ajuSobre;
    private javax.swing.JButton btnCalculos;
    private javax.swing.JButton btnComunicacao;
    private javax.swing.JButton btnEscalas;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnHorarios;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenuItem cadCargos;
    private javax.swing.JMenuItem cadCentroCusto;
    private javax.swing.JMenuItem cadDepartamentos;
    private javax.swing.JMenuItem cadEmpresa;
    private javax.swing.JMenuItem cadEscalas;
    private javax.swing.JMenuItem cadFuncionarios;
    private javax.swing.JMenuItem cadHorarios;
    private javax.swing.JMenuItem cadJustificativas;
    private javax.swing.JMenuItem cadTabelaFeriados;
    private javax.swing.JMenuItem cadUsuarios;
    private javax.swing.JMenuItem comEnviarReceber;
    private javax.swing.JMenuItem comRecebeAFD;
    private javax.swing.JLabel contAfastados;
    private javax.swing.JLabel contAusentes;
    private javax.swing.JLabel contPresentes;
    private javax.swing.JLabel contTotal;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JLabel lblAfastados;
    private javax.swing.JLabel lblAuxentes;
    private javax.swing.JLabel lblPresentes;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenuItem manBanco;
    private javax.swing.JMenuItem manConfiguracoes;
    private javax.swing.JMenuItem manEquipamentos;
    private javax.swing.JMenuItem manServicosOnline;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenu menuComunicacao;
    private javax.swing.JMenu menuManutencao;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JPanel pContFuncionarios;
    private javax.swing.JPanel pEspacador;
    private javax.swing.JPanel pMenu;
    private javax.swing.JMenuItem relACJEF;
    private javax.swing.JMenuItem relAFDT;
    private javax.swing.JMenuItem relAbsenteismo;
    private javax.swing.JMenuItem relAfastamentos;
    private javax.swing.JMenuItem relAtivos;
    private javax.swing.JMenuItem relBanco;
    private javax.swing.JMenuItem relCartaoPonto;
    private javax.swing.JMenuItem relDemitidos;
    private javax.swing.JMenuItem relEscalas;
    private javax.swing.JMenu relFiscais;
    private javax.swing.JMenu relFuncionarios;
    private javax.swing.JMenuItem relHorarios;
    // End of variables declaration//GEN-END:variables
}
